"""Enums normalizados usados em todo o domínio."""

from __future__ import annotations

from enum import Enum


class PropertyType(str, Enum):
    APARTMENT = "APARTMENT"
    HOUSE = "HOUSE"
    LAND = "LAND"
    COMMERCIAL = "COMMERCIAL"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"


class LegalOwnershipType(str, Enum):
    FULL_OWNERSHIP = "FULL_OWNERSHIP"
    AUTONOMOUS_UNIT = "AUTONOMOUS_UNIT"
    UNDIVIDED_SHARE = "UNDIVIDED_SHARE"
    MARITAL_SHARE = "MARITAL_SHARE"
    USUFRUCT = "USUFRUCT"
    BARE_OWNERSHIP = "BARE_OWNERSHIP"
    HEREDITARY_RIGHT = "HEREDITARY_RIGHT"
    SURFACE_RIGHT = "SURFACE_RIGHT"
    UNKNOWN = "UNKNOWN"


class LegalStatus(str, Enum):
    ACCEPTED = "ACCEPTED"
    AUTOMATICALLY_REJECTED = "AUTOMATICALLY_REJECTED"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"


class OccupancyStatus(str, Enum):
    VACANT = "VACANT"
    OCCUPIED_BY_OWNER = "OCCUPIED_BY_OWNER"
    OCCUPIED_BY_TENANT = "OCCUPIED_BY_TENANT"
    OCCUPIED_UNKNOWN = "OCCUPIED_UNKNOWN"
    UNKNOWN = "UNKNOWN"


class VisitStatus(str, Enum):
    AVAILABLE = "AVAILABLE"
    BY_APPOINTMENT = "BY_APPOINTMENT"
    NOT_AVAILABLE = "NOT_AVAILABLE"
    UNKNOWN = "UNKNOWN"


class KeyDeliveryStatus(str, Enum):
    IMMEDIATE = "IMMEDIATE"
    SCHEDULED = "SCHEDULED"
    NOT_AVAILABLE = "NOT_AVAILABLE"
    UNKNOWN = "UNKNOWN"


class RenovationLevel(str, Enum):
    LIGHT_WORKS = "LIGHT_WORKS"
    MEDIUM_WORKS = "MEDIUM_WORKS"
    FULL_RENOVATION = "FULL_RENOVATION"
    POSSIBLE_STRUCTURAL_WORKS = "POSSIBLE_STRUCTURAL_WORKS"
    RUIN_OR_RECONSTRUCTION = "RUIN_OR_RECONSTRUCTION"
    NOT_IDENTIFIED = "NOT_IDENTIFIED"


class SaleMethod(str, Enum):
    AUCTION = "AUCTION"
    ELECTRONIC_AUCTION = "ELECTRONIC_AUCTION"
    SEALED_PROPOSAL = "SEALED_PROPOSAL"
    PRIVATE_NEGOTIATION = "PRIVATE_NEGOTIATION"
    NORMAL_SALE = "NORMAL_SALE"
    UNKNOWN = "UNKNOWN"


class ListingStatus(str, Enum):
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    REMOVED = "REMOVED"
    SOLD = "SOLD"
    ENDED = "ENDED"


class Classification(str, Enum):
    PRIORITY_HIGH = "PRIORITY_HIGH"
    ANALYZE = "ANALYZE"
    WATCH = "WATCH"
    LOW_PRIORITY = "LOW_PRIORITY"
    EXCLUDE = "EXCLUDE"


class GeolocationAccuracy(str, Enum):
    ADDRESS = "ADDRESS"
    POSTAL_CODE = "POSTAL_CODE"
    PARISH = "PARISH"
    MUNICIPALITY = "MUNICIPALITY"
    APPROXIMATE = "APPROXIMATE"
    UNKNOWN = "UNKNOWN"


class EventType(str, Enum):
    NEW_LISTING = "NEW_LISTING"
    PRICE_DECREASE = "PRICE_DECREASE"
    PRICE_INCREASE = "PRICE_INCREASE"
    STATUS_CHANGED = "STATUS_CHANGED"
    AUCTION_END_CHANGED = "AUCTION_END_CHANGED"
    REMOVED = "REMOVED"
    SOLD = "SOLD"
    REACTIVATED = "REACTIVATED"
    LEGAL_ALERT_FOUND = "LEGAL_ALERT_FOUND"
    OCCUPANCY_CHANGED = "OCCUPANCY_CHANGED"
    SOURCE_FAILED = "SOURCE_FAILED"


class SourceRunStatus(str, Enum):
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    SKIPPED = "SKIPPED"


class UserDecisionType(str, Enum):
    NEW = "NEW"
    FAVORITE = "FAVORITE"
    ANALYZE = "ANALYZE"
    CONTACT = "CONTACT"
    VISIT = "VISIT"
    WATCH = "WATCH"
    REJECTED = "REJECTED"
    PURCHASED = "PURCHASED"
    SOLD = "SOLD"


class MatchStatus(str, Enum):
    POSSIBLE_DUPLICATE = "POSSIBLE_DUPLICATE"
    CONFIRMED_DUPLICATE = "CONFIRMED_DUPLICATE"
    NOT_DUPLICATE = "NOT_DUPLICATE"
